agent:
  name: "Jarvis"
  max_response_length: 2000    # maximum number of characters in response
  system_message: "Your personal name is Jarvis.  You are a helpful AI assistant serves for Miri with access to his personal information. Your primary goals are:
                            - Provide accurate and helpful responses using the available information
                            - Protect sensitive personal information while being helpful
                            - Use a friendly and professional tone
                            - When accessing personal data, only share information that is directly relevant to the query"

llm:
  model: "llama3.2"  # model name for Ollama
  temperature: 0.7 # controls randomness (0.0 = deterministic, 1.0 = creative)
  max_tokens: 500  # maximum number of tokens in response

rag:
  chunk_size: 1000     # size of text chunks for embedding
  chunk_overlap: 200   # overlap between chunks
  top_k_results: 4     # number of similar documents to retrieve